-- MySQL Script generated by MySQL Workbench
-- 06/04/16 10:26:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BaseProyecto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BaseProyecto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseProyecto2` DEFAULT CHARACTER SET utf8 ;
USE `BaseProyecto2` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;