-- MySQL Script generated by MySQL Workbench
-- 06/04/16 10:26:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BaseProyecto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BaseProyecto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseProyecto2` DEFAULT CHARACTER SET utf8 ;
USE `BaseProyecto2` ;

-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Color` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`CategoriaPrincipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`CategoriaPrincipal` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Subcategoria` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idCategoriaPrincipal` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idCategoriaPrincipal_idx` (`idCategoriaPrincipal` ASC),
  CONSTRAINT `FK_idCategoriaPrincipal`
    FOREIGN KEY (`idCategoriaPrincipal`)
    REFERENCES `BaseProyecto2`.`CategoriaPrincipal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`TipoFermentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`TipoFermentacion` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Estilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Estilo` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Cuerpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Cuerpo` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Cerveza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Cerveza` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `tiempoFermentacion` INT NULL,
  `temperatura` INT NULL,
  `precio` INT NULL,
  `idTipoFermentacion` INT NULL,
  `idColor` INT NULL,
  `idEstilo` INT NULL,
  `idCuerpo` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idTipoFermentacion_idx` (`idTipoFermentacion` ASC),
  INDEX `idColor_idx` (`idColor` ASC),
  INDEX `idEstilo_idx` (`idEstilo` ASC),
  INDEX `FK_idCuerpo_idx` (`idCuerpo` ASC),
  CONSTRAINT `FK_idTipoFermentacion`
    FOREIGN KEY (`idTipoFermentacion`)
    REFERENCES `BaseProyecto2`.`TipoFermentacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idColor`
    FOREIGN KEY (`idColor`)
    REFERENCES `BaseProyecto2`.`Color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idEstilo`
    FOREIGN KEY (`idEstilo`)
    REFERENCES `BaseProyecto2`.`Estilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idCuerpo`
    FOREIGN KEY (`idCuerpo`)
    REFERENCES `BaseProyecto2`.`Cuerpo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Bitacora` (
  `id` INT NOT NULL,
  `precioAnterior` INT NULL,
  `nuevoPrecio` INT NULL,
  `idCerveza` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_idCerveza_idx` (`idCerveza` ASC),
  CONSTRAINT `FK_idCerveza`
    FOREIGN KEY (`idCerveza`)
    REFERENCES `BaseProyecto2`.`Cerveza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Pais` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Estado` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `idPais` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_Estado_idPais_idx` (`idPais` ASC),
  CONSTRAINT `FK_Estado_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `BaseProyecto2`.`Pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Cliente` (
  `id` INT NOT NULL,
  `rutaFoto` VARCHAR(45) NULL,
  `direccionEspecifica` VARCHAR(45) NULL,
  `idPersona` INT NULL,
  `idEstado` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_Cliente_idPersona_idx` (`idPersona` ASC),
  INDEX `FK_Cliente_idEstado_idx` (`idEstado` ASC),
  CONSTRAINT `FK_Cliente_idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `BaseProyecto2`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Cliente_idEstado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `BaseProyecto2`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Empleado` (
  `id` INT NOT NULL,
  `fechaIngreso` DATETIME NULL,
  `idPersona` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_Empleado_idPersona_idx` (`idPersona` ASC),
  CONSTRAINT `FK_Empleado_idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `BaseProyecto2`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`Usuario` (
  `id` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `idPersona` INT NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Usuario_idPersona_idx` (`idPersona` ASC),
  CONSTRAINT `FK_Usuario_idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `BaseProyecto2`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProyecto2`.`CervezasXPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseProyecto2`.`CervezasXPersona` (
  `id` INT NOT NULL,
  `idPersona` INT NULL,
  `idCerveza` INT NULL,
  `cantidad` VARCHAR(45) NULL,
  `usuarioCreacion` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `usuarioUltimaModificacion` VARCHAR(45) NULL,
  `FechaUltimaModificacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_CervezasXPersona_idPersona_idx` (`idPersona` ASC),
  INDEX `FK_CervezasXPersona_idCerveza_idx` (`idCerveza` ASC),
  CONSTRAINT `FK_CervezasXPersona_idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `BaseProyecto2`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CervezasXPersona_idCerveza`
    FOREIGN KEY (`idCerveza`)
    REFERENCES `BaseProyecto2`.`Cerveza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
