CREATE DEFINER=`root@localhost` PROCEDURE `SELECT_COMPRADORES`(IN pLETRA VARCHAR(10))
BEGIN
	SELECT P.NOMBRE, P.APELLIDO
	FROM CERVEZAXCLIENTE CXC INNER JOIN  PERSONA P
	WHERE CXC.IDCLIENTE= P.ID AND p.NOMBRE LIKE(''+pLETRA+'%');
END