CREATE DEFINER=`root`@`localhost` PROCEDURE `SELECT_COMPRADORES`(IN pLETRA VARCHAR(5))
BEGIN
	SELECT P.NOMBRE, P.APELLIDO
	FROM CERVEZASXPERSONA CXP INNER JOIN  PERSONA P
	WHERE CXP.IDPERSONA= P.ID AND p.NOMBRE LIKE (pLETRA+'%');
END
