#FECHA: 6 JUNIO 2016
#AUTOR: MARIELA BARRANTES
#DESCRIPCION: STORED PROCEDURE - DELETE

DELIMITER //

#DELETES CATALOGOS
#DELETE COLOR
CREATE procedure DELETE_COLOR(IN pID INT)
BEGIN
	DELETE FROM COLOR
    WHERE id=pID;
END//

#DELETE CUERPO
CREATE procedure DELETE_CUERPO(IN pID INT)
BEGIN
	DELETE FROM CUERPO
    WHERE id=pID;
END//

#DELETE ESTADO
CREATE procedure DELETE_ESTADO(IN pID INT)
BEGIN
	DELETE FROM ESTADO
    WHERE id=pID;
END//

#DELETE ESTILO
CREATE procedure DELETE_ESTILO(IN pID INT
BEGIN
	DELETE FROM ESTILO
    WHERE id=pID;
END//

#DELETE PAIS
CREATE procedure DELETE_PAIS(IN pID INT
BEGIN
	DELETE FROM PAIS
    WHERE id=pID;
END//

#DELETE CATEFORIA PRINCIPAL
CREATE procedure DELETE_CATEGORIA_PRINCIPAL(IN pID INT
BEGIN
	DELETE FROM CATEGORIAPRINCIPAL
    WHERE id=pID;
END//

#DELETE SUBCATEGORIA
CREATE procedure DELETE_SUBCATEGORIA(IN pID INT)
BEGIN
	DELETE FROM SUBCATEGORIA
    WHERE id=pID;
END//

#DELETE TIPO FERMENTACION
CREATE procedure DELETE_TIPO_FERMENTACION(IN pID INT)
BEGIN
	DELETE FROM TIPOFERMENTACION
    WHERE id=pID;
END//



#---------------------------------------------------------------------------------------------
#DELETE TABLAS

#DELETE CERVEZA
CREATE procedure DELETE_CERVEZA(IN pNOMBRE varchar(45), IN pDESCRIPCION varchar(45), IN pTFERMENTACION INT, IN pTEMPERATURA INT, IN pPRECIO INT, IN pID_TIPOF INT, IN pID_COLOR INT, IN pID_ESTILO INT, IN pID_CUERPO INT)
BEGIN
	DELETE FROM COLOR
    WHERE =;
END//

#DELETE PERSONA
CREATE procedure DELETE_PERSONA(IN pNOMBRE varchar(45), IN pAPELLIDO varchar(45), IN pCEDULA varchar(45))
BEGIN
	INSERT INTO PERSONA(nombre, apellido, cedula)
    VALUES(pNOMBRE, pAPELLIDO, pCEDULA);
END//

#DELETE CXP
CREATE procedure DELETE_CXP(IN pID_PERSONA INT, IN pID_CERVEZA INT)
BEGIN
	INSERT INTO cervezasxpersona(idPersona, idCerveza)
    VALUES(pPERSONA, pCERVEZA);
END//

#DELETE CLIENTE
CREATE procedure DELETE_CLIENTE(IN pRUTAFOTO varchar(45), IN pDIRECCION varchar(45), IN pID_PERSONA INT, IN pID_ESTADO INT)
BEGIN
	INSERT INTO CLIENTE(rutaFoto, direccionEspecifica, idPersona, idEstado)
    VALUES(pRUTAFOTO, pDIRECCION, pID_PERSONA, pID_ESTADO);
END//

#DELETE EMPLEADO
CREATE procedure DELETE_EMPLEADO(IN pFECHAINGRESO date, IN pID_PERSONA INT)
BEGIN
	INSERT INTO EMPLEADO(fechaIngreso, idPersona)
    VALUES(pFECHAINGRESO, pID_PERSONA);
END//

#DELETE USUARIO
CREATE procedure DELETE_USUARIO(IN pNOMBRE varchar(45), IN pCONTRASENA varchar(45), IN pID_PERSONA INT)
BEGIN
	INSERT INTO USUARIO(nombreUsuario, contrasena, idPersona)
    VALUES(pNOMBRE, pCONTRASENA, pID_PERSONA);
END//

#DELETE BITACORA
CREATE procedure DELETE_BITACORA(IN pPRECIOANTERIOR INT, IN pPRECIONUEVO INT, IN pIDCERVEZA INT)
BEGIN
	INSERT INTO BITACORA(precioAnterior, nuevoPrecio, idCerveza)
    VALUES(pPRECIOANTERIOR, pPRECIONUEVO, pIDCERVEZA);
END//

DELIMITER ;